### ISSUE TITLE
Implement a Brython module

### ISSUE THREAD

**Issue by AngelaRemolina** [angelasofiaremolinagutierrez/PyZombis#3]
PyZombis’ current web interpreter, Skulpt, has blocked the implementation of some complex exercises due to of its limitations with some libraries (see issue [#61](https://github.com/PyAr/PyZombis/issues/61)). These reasons being on top of the fact that Skulpt is based on Python 2.x, a version [sunsetted ](https://www.python.org/doc/sunset-python-2/)by the Python Software Foundation (PSF) since January 1, 2020. 

PyZombis uses Skulpt because it is the interpreter than works with Runestone. The idea is to implement a Runestone module that allows to load Brython (which is an interpreter that supports the latest stable releases of Python, plus main libraries) when is needed.

This can only be done once issue #1 is solved, because it is needed that the project uses the latest version of Runestone.

**Comment by reingart** [comment]
Great! try split this in at least 3 tickets:
1. Visual (js/css/etc.)
2. Run code
3. Run unit tests

**Comment by AngelaRemolina** [comment]
Ok done! here they are:

1. Visual part will be solved inside RunestoneComponents repository https://github.com/angelasofiaremolinagutierrez/RunestoneComponents/milestone/1
2. Exercises using new component (see #8)
3. Unit/integration test (see #7)

I stand by the runestone activecode aproach, so I will close this issue.
