### ISSUE TITLE
Implement a Runestone component for Brython

### ISSUE THREAD

**Issue by reingart** [angelasofiaremolinagutierrez/PyZombis#6]
For example: https://github.com/RunestoneInteractive/RunestoneComponents/pull/825/files

Compare both approaches & talk with Runestone developers which one is the best

**Comment by AngelaRemolina** [comment]
See: https://github.com/angelasofiaremolinagutierrez/RunestoneComponents/milestone/1 for more detail on this issue

**Comment by AngelaRemolina** [comment]
The runestone module is done :) (see [this milestone](https://github.com/angelasofiaremolinagutierrez/RunestoneComponents/milestone/1) for more details).
